/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MainLayoutImport } from './routes/_main-layout'
import { Route as MainLayoutIndexImport } from './routes/_main-layout/index'
import { Route as MainLayoutDocsValidationOnIndexImport } from './routes/_main-layout/docs/validation-on/index'
import { Route as MainLayoutDocsValidationDefaultsIndexImport } from './routes/_main-layout/docs/validation-defaults/index'
import { Route as MainLayoutDocsValidationComponentIndexImport } from './routes/_main-layout/docs/validation-component/index'
import { Route as MainLayoutDocsTextareaIndexImport } from './routes/_main-layout/docs/textarea/index'
import { Route as MainLayoutDocsTextIndexImport } from './routes/_main-layout/docs/text/index'
import { Route as MainLayoutDocsSelectIndexImport } from './routes/_main-layout/docs/select/index'
import { Route as MainLayoutDocsPasswordIndexImport } from './routes/_main-layout/docs/password/index'
import { Route as MainLayoutDocsLoadingIndexImport } from './routes/_main-layout/docs/loading/index'
import { Route as MainLayoutDocsIntroductionIndexImport } from './routes/_main-layout/docs/introduction/index'
import { Route as MainLayoutDocsIntegerDecimalIndexImport } from './routes/_main-layout/docs/integer-decimal/index'
import { Route as MainLayoutDocsCustomValidationsIndexImport } from './routes/_main-layout/docs/custom-validations/index'
import { Route as MainLayoutDocsCalendarIndexImport } from './routes/_main-layout/docs/calendar/index'
import { Route as MainLayoutDocsBeforeAfterIndexImport } from './routes/_main-layout/docs/before-after/index'

// Create/Update Routes

const MainLayoutRoute = MainLayoutImport.update({
  id: '/_main-layout',
  getParentRoute: () => rootRoute,
} as any)

const MainLayoutIndexRoute = MainLayoutIndexImport.update({
  path: '/',
  getParentRoute: () => MainLayoutRoute,
} as any)

const MainLayoutDocsValidationOnIndexRoute =
  MainLayoutDocsValidationOnIndexImport.update({
    path: '/docs/validation-on/',
    getParentRoute: () => MainLayoutRoute,
  } as any)

const MainLayoutDocsValidationDefaultsIndexRoute =
  MainLayoutDocsValidationDefaultsIndexImport.update({
    path: '/docs/validation-defaults/',
    getParentRoute: () => MainLayoutRoute,
  } as any)

const MainLayoutDocsValidationComponentIndexRoute =
  MainLayoutDocsValidationComponentIndexImport.update({
    path: '/docs/validation-component/',
    getParentRoute: () => MainLayoutRoute,
  } as any)

const MainLayoutDocsTextareaIndexRoute =
  MainLayoutDocsTextareaIndexImport.update({
    path: '/docs/textarea/',
    getParentRoute: () => MainLayoutRoute,
  } as any)

const MainLayoutDocsTextIndexRoute = MainLayoutDocsTextIndexImport.update({
  path: '/docs/text/',
  getParentRoute: () => MainLayoutRoute,
} as any)

const MainLayoutDocsSelectIndexRoute = MainLayoutDocsSelectIndexImport.update({
  path: '/docs/select/',
  getParentRoute: () => MainLayoutRoute,
} as any)

const MainLayoutDocsPasswordIndexRoute =
  MainLayoutDocsPasswordIndexImport.update({
    path: '/docs/password/',
    getParentRoute: () => MainLayoutRoute,
  } as any)

const MainLayoutDocsLoadingIndexRoute = MainLayoutDocsLoadingIndexImport.update(
  {
    path: '/docs/loading/',
    getParentRoute: () => MainLayoutRoute,
  } as any,
)

const MainLayoutDocsIntroductionIndexRoute =
  MainLayoutDocsIntroductionIndexImport.update({
    path: '/docs/introduction/',
    getParentRoute: () => MainLayoutRoute,
  } as any)

const MainLayoutDocsIntegerDecimalIndexRoute =
  MainLayoutDocsIntegerDecimalIndexImport.update({
    path: '/docs/integer-decimal/',
    getParentRoute: () => MainLayoutRoute,
  } as any)

const MainLayoutDocsCustomValidationsIndexRoute =
  MainLayoutDocsCustomValidationsIndexImport.update({
    path: '/docs/custom-validations/',
    getParentRoute: () => MainLayoutRoute,
  } as any)

const MainLayoutDocsCalendarIndexRoute =
  MainLayoutDocsCalendarIndexImport.update({
    path: '/docs/calendar/',
    getParentRoute: () => MainLayoutRoute,
  } as any)

const MainLayoutDocsBeforeAfterIndexRoute =
  MainLayoutDocsBeforeAfterIndexImport.update({
    path: '/docs/before-after/',
    getParentRoute: () => MainLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main-layout': {
      id: '/_main-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_main-layout/': {
      id: '/_main-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutIndexImport
      parentRoute: typeof MainLayoutImport
    }
    '/_main-layout/docs/before-after/': {
      id: '/_main-layout/docs/before-after/'
      path: '/docs/before-after'
      fullPath: '/docs/before-after'
      preLoaderRoute: typeof MainLayoutDocsBeforeAfterIndexImport
      parentRoute: typeof MainLayoutImport
    }
    '/_main-layout/docs/calendar/': {
      id: '/_main-layout/docs/calendar/'
      path: '/docs/calendar'
      fullPath: '/docs/calendar'
      preLoaderRoute: typeof MainLayoutDocsCalendarIndexImport
      parentRoute: typeof MainLayoutImport
    }
    '/_main-layout/docs/custom-validations/': {
      id: '/_main-layout/docs/custom-validations/'
      path: '/docs/custom-validations'
      fullPath: '/docs/custom-validations'
      preLoaderRoute: typeof MainLayoutDocsCustomValidationsIndexImport
      parentRoute: typeof MainLayoutImport
    }
    '/_main-layout/docs/integer-decimal/': {
      id: '/_main-layout/docs/integer-decimal/'
      path: '/docs/integer-decimal'
      fullPath: '/docs/integer-decimal'
      preLoaderRoute: typeof MainLayoutDocsIntegerDecimalIndexImport
      parentRoute: typeof MainLayoutImport
    }
    '/_main-layout/docs/introduction/': {
      id: '/_main-layout/docs/introduction/'
      path: '/docs/introduction'
      fullPath: '/docs/introduction'
      preLoaderRoute: typeof MainLayoutDocsIntroductionIndexImport
      parentRoute: typeof MainLayoutImport
    }
    '/_main-layout/docs/loading/': {
      id: '/_main-layout/docs/loading/'
      path: '/docs/loading'
      fullPath: '/docs/loading'
      preLoaderRoute: typeof MainLayoutDocsLoadingIndexImport
      parentRoute: typeof MainLayoutImport
    }
    '/_main-layout/docs/password/': {
      id: '/_main-layout/docs/password/'
      path: '/docs/password'
      fullPath: '/docs/password'
      preLoaderRoute: typeof MainLayoutDocsPasswordIndexImport
      parentRoute: typeof MainLayoutImport
    }
    '/_main-layout/docs/select/': {
      id: '/_main-layout/docs/select/'
      path: '/docs/select'
      fullPath: '/docs/select'
      preLoaderRoute: typeof MainLayoutDocsSelectIndexImport
      parentRoute: typeof MainLayoutImport
    }
    '/_main-layout/docs/text/': {
      id: '/_main-layout/docs/text/'
      path: '/docs/text'
      fullPath: '/docs/text'
      preLoaderRoute: typeof MainLayoutDocsTextIndexImport
      parentRoute: typeof MainLayoutImport
    }
    '/_main-layout/docs/textarea/': {
      id: '/_main-layout/docs/textarea/'
      path: '/docs/textarea'
      fullPath: '/docs/textarea'
      preLoaderRoute: typeof MainLayoutDocsTextareaIndexImport
      parentRoute: typeof MainLayoutImport
    }
    '/_main-layout/docs/validation-component/': {
      id: '/_main-layout/docs/validation-component/'
      path: '/docs/validation-component'
      fullPath: '/docs/validation-component'
      preLoaderRoute: typeof MainLayoutDocsValidationComponentIndexImport
      parentRoute: typeof MainLayoutImport
    }
    '/_main-layout/docs/validation-defaults/': {
      id: '/_main-layout/docs/validation-defaults/'
      path: '/docs/validation-defaults'
      fullPath: '/docs/validation-defaults'
      preLoaderRoute: typeof MainLayoutDocsValidationDefaultsIndexImport
      parentRoute: typeof MainLayoutImport
    }
    '/_main-layout/docs/validation-on/': {
      id: '/_main-layout/docs/validation-on/'
      path: '/docs/validation-on'
      fullPath: '/docs/validation-on'
      preLoaderRoute: typeof MainLayoutDocsValidationOnIndexImport
      parentRoute: typeof MainLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  MainLayoutRoute: MainLayoutRoute.addChildren({
    MainLayoutIndexRoute,
    MainLayoutDocsBeforeAfterIndexRoute,
    MainLayoutDocsCalendarIndexRoute,
    MainLayoutDocsCustomValidationsIndexRoute,
    MainLayoutDocsIntegerDecimalIndexRoute,
    MainLayoutDocsIntroductionIndexRoute,
    MainLayoutDocsLoadingIndexRoute,
    MainLayoutDocsPasswordIndexRoute,
    MainLayoutDocsSelectIndexRoute,
    MainLayoutDocsTextIndexRoute,
    MainLayoutDocsTextareaIndexRoute,
    MainLayoutDocsValidationComponentIndexRoute,
    MainLayoutDocsValidationDefaultsIndexRoute,
    MainLayoutDocsValidationOnIndexRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_main-layout"
      ]
    },
    "/_main-layout": {
      "filePath": "_main-layout.tsx",
      "children": [
        "/_main-layout/",
        "/_main-layout/docs/before-after/",
        "/_main-layout/docs/calendar/",
        "/_main-layout/docs/custom-validations/",
        "/_main-layout/docs/integer-decimal/",
        "/_main-layout/docs/introduction/",
        "/_main-layout/docs/loading/",
        "/_main-layout/docs/password/",
        "/_main-layout/docs/select/",
        "/_main-layout/docs/text/",
        "/_main-layout/docs/textarea/",
        "/_main-layout/docs/validation-component/",
        "/_main-layout/docs/validation-defaults/",
        "/_main-layout/docs/validation-on/"
      ]
    },
    "/_main-layout/": {
      "filePath": "_main-layout/index.tsx",
      "parent": "/_main-layout"
    },
    "/_main-layout/docs/before-after/": {
      "filePath": "_main-layout/docs/before-after/index.tsx",
      "parent": "/_main-layout"
    },
    "/_main-layout/docs/calendar/": {
      "filePath": "_main-layout/docs/calendar/index.tsx",
      "parent": "/_main-layout"
    },
    "/_main-layout/docs/custom-validations/": {
      "filePath": "_main-layout/docs/custom-validations/index.tsx",
      "parent": "/_main-layout"
    },
    "/_main-layout/docs/integer-decimal/": {
      "filePath": "_main-layout/docs/integer-decimal/index.tsx",
      "parent": "/_main-layout"
    },
    "/_main-layout/docs/introduction/": {
      "filePath": "_main-layout/docs/introduction/index.tsx",
      "parent": "/_main-layout"
    },
    "/_main-layout/docs/loading/": {
      "filePath": "_main-layout/docs/loading/index.tsx",
      "parent": "/_main-layout"
    },
    "/_main-layout/docs/password/": {
      "filePath": "_main-layout/docs/password/index.tsx",
      "parent": "/_main-layout"
    },
    "/_main-layout/docs/select/": {
      "filePath": "_main-layout/docs/select/index.tsx",
      "parent": "/_main-layout"
    },
    "/_main-layout/docs/text/": {
      "filePath": "_main-layout/docs/text/index.tsx",
      "parent": "/_main-layout"
    },
    "/_main-layout/docs/textarea/": {
      "filePath": "_main-layout/docs/textarea/index.tsx",
      "parent": "/_main-layout"
    },
    "/_main-layout/docs/validation-component/": {
      "filePath": "_main-layout/docs/validation-component/index.tsx",
      "parent": "/_main-layout"
    },
    "/_main-layout/docs/validation-defaults/": {
      "filePath": "_main-layout/docs/validation-defaults/index.tsx",
      "parent": "/_main-layout"
    },
    "/_main-layout/docs/validation-on/": {
      "filePath": "_main-layout/docs/validation-on/index.tsx",
      "parent": "/_main-layout"
    }
  }
}
ROUTE_MANIFEST_END */
